import type { Metadata } from "next";
import "./globals.css";
import { Preloader } from "@/components/ui/preloader";
import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <Preloader />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
